### ISSUE TITLE
can't add multiple instances of jvb

### ISSUE THREAD

**Issue by oele-dev** [nickdannenberg/netdata-jitsi-videobridge#1]
I added another jvb instance but it is not displayed in the control panel and not is it loaded when debugging the module.

Regards

**Comment by nickdannenberg** [comment]
Hello,

I just tested this locally and it seems to work. My config `/etc/netdata/python.d/jvb.conf` looks like this:

```
jvb1:   
        name: 'jvb1'
        url: 'http://jvb1:8080/colibri/stats'

jvb2:   
        name: 'jvb2'
        url: 'http://jvb2:8080/colibri/stats'

localhost:
        name: 'local'
        url: 'http://localhost:8080/colibri/stats'
```

The section for jvb2 is not visible in netdata, but this is because the netdata host cannot reach port 8080 on that host.
Can you please verify that you can reach port 8080 on your jvbs from the netdata host?

Regards
